config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create,:edit,:update]
  get 'users/:id/save_user_edit' ,to: 'users#save_user_edit'

  
  resources :productions, only: [:show, :create, :destroy, :new]
  
  get 'productions/:id/transaction', to: 'productions#transaction'
  get 'productions/:id/buy', to: 'productions#buy'
  
  #gitのコミット用
  
  get 'create_productions', to: 'productions#create'
  post 'send_comment', to: 'productions#save_comment'
  post 'send_transaction_comment', to: 'productions#send_transaction_comment'
  
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :production
  
  
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/production.rb
class Production < ApplicationRecord
  belongs_to :user
  has_many :comments
  
  
  validates :user_id, presence: true
  validates :production_title, presence: true, length: { maximum: 255 }
  validates :production_picture, presence: true
  validates :production_information, presence: true, length: { maximum: 500 }
  validates :production_genre, presence: true, length: { maximum: 255 }
  # ↑　ここは変更しなきゃダメ
  validates :production_season, presence: true, length: { maximum: 10 }

  mount_uploader :production_picture, PictureUploader

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :nickname, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  has_many :productions
  has_many :comments
  # has_secure_password :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  
  
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in
 
  def create
    # render　で　toppage/index　に飛ばした時用のproduction.all
    @productions = Production.all
    
    @production_comment = current_user.comments.build(comment_params)
    if @production_comment.save
      flash[:success] = 'コメントを送信しました。'
      # redirect_to 'productions/new'
      render 'toppages/index'
    else
      # @comment = current_user.productions.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'コメントの送信に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
 
  end


  def new

  end
  
  private
  
 
  
end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  before_action :require_user_logged_in,only: [:create,:new,:update,:buy]
  
  def index
  end

  def show
    @production_show = Production.find(params[:id])
    @display_comment = Comment.where(production_id: params[:id]).where(transaction_comment: false).all.order(created_at: "DESC")
    # productionのidが欲しい
    @production_comment = current_user.comments.new
  end

  def new
    #制作物投稿フォーム作成のため空のインスタンスを生成
    @production = current_user.productions.build
  end

  def create
    @productions = Production.all
    @production = current_user.productions.new(production_params)
    if @production.save
      flash[:success] = '制作物を出品しました。'
      # redirect_to 'productions/new'
      render 'toppages/index'
    else
      @production = current_user.productions.order('created_at DESC').page(params[:page])
      flash.now[:danger] = '制作物出品に失敗しました。'
      render 'toppages/index'
    end
    
  end

  def destroy
  end
 
  def update
 
  end
  
  def save_comment
    # render　で　toppage/index　に飛ばした時用のproduction.all
    
    @this_production = Production.find(comment_params[:production_id])
    # @productions = Production.all
    @production_comment = current_user.comments.build(comment_params)
    if @production_comment.save
      flash[:success] = 'コメントを送信しました。'
      puts('成功しました')
      redirect_to @this_production
    else
      flash[:danger] = 'コメントの送信に失敗しました。'
      puts('失敗しました')
      redirect_to @this_production
    end
  end
  
  def transaction
    #取引画面の処理はここに書く
    @production = Production.find(params[:id])
    @seller = @production.user
    @buyer = User.find(@production.buyer)
  
    @production_comment = current_user.comments.new
    @transaction_display_comment = Comment.where(production_id: params[:id]).where(transaction_comment: true).all.order(created_at: "DESC")
  end
  
  def send_transaction_comment
    # render　で　toppage/index　に飛ばした時用のproduction.all
    
    @this_production = Production.find(comment_params[:production_id])
    # @productions = Production.all
    @production_comment = current_user.comments.build(comment_params)
    if @production_comment.save
      flash[:success] = 'コメントを送信しました。'
      puts('成功しました')
      redirect_to :back
    else
      flash[:danger] = 'コメントの送信に失敗しました。'
      puts('失敗しました')
      redirect_to :back
    end
  end
  
  def buy
    #購入者のid　売却者のidの処理をここに記述する
    @production = Production.find(params[:id])
    @production.status = false
    @production.buyer = current_user.id
    @production.seller = @production.user.id
    if @production.save
      flash[:success] = '購入に成功しました'
      redirect_to :controller => "productions", :action => "transaction"
    else 
      flash[:success] = '購入に失敗しました'
      redirect_to @production
    end
  end
  
  
  private
  
  def production_params
    params.require(:production).permit(:production_title, :production_picture, :production_information, :production_genre, :production_season)
  end
  
  def comment_params
    params.require(:comment).permit(:content,:production_id,:transaction_comment)
  end
  
  def transaction_params
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
     email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @productions = Production.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  
  def index
    # @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @productions = current_user.productions
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    #@current_user　が使える
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_edit_params)
      flash[:success] = '編集を保存しました。'
      redirect_to @user
    else
      flash.now[:danger] = '編集の保存に失敗しました。'
      redirect_to :back
    end
  end
  
  def save_user_edit
  end
  
  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
  end
  
  def user_edit_params
    params.require(:user).permit(:nickname, :email, :password,:realname,:postalcode,:address,:image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def current_production
    if params[:id].present?
    @current_production ||= Production.find_by(id: params[:id])
    end
    
  end

  def logged_in?
    !!current_user
  end
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>

  <div class="alert alert-warning">
    <ul>
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

  <div class="alert alert-
<%= message_type %>
">
<%= message %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">壁面マッチングサイト</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          
          
          
          <% if logged_in? %>
            <li><%= link_to '出品する', new_production_path %></li>
            <li><%= link_to 'マイページ', current_user %></li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
  
            
          <!--<li><a href="#">新規登録</a></li>-->
          <% else %>
            <li><%= link_to '新規登録', signup_path %></li>          
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
          
          
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Hekimen-Matching</title>
    
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>
    <div class="container">
      
    <%= render 'layouts/flash_messages' %>

    <%= yield %>

    </div>
  </body>
</html>

app/views/productions/_productions.html.erb
    <% @productions.each do |production| %>
    
      <div class="item">
        <div class="col-md-3 col-sm-4 col-xs-12">
          
          
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <%= production.production_picture %>
              <!--<= image_tag(production.production_picture) %>-->
            </div>
            <div class="panel-body">
              <p class="item-title"> <%= production.production_title %> </p>
            </div>
          
          </div>
          
          
        </div>
        
        
      </div>
      
    <% end %>

app/views/productions/buy.html.erb
please find me 

app/views/productions/create.html.erb
<h1>出品・シェアに成功しました。</h1>

app/views/productions/destroy.html.erb
<h1>Productions#destroy</h1>
<p>Find me in app/views/productions/destroy.html.erb</p>

app/views/productions/index.html.erb
<h1>Productions#index</h1>
<p>Find me in app/views/productions/index.html.erb</p>

app/views/productions/new.html.erb
<%= form_for(@production) do |f| %>
        <div class="form-group">
          <%= f.label :'制作物名' %>
          <%= f.text_area :production_title, class: 'form-control', rows: 3 %>
        </div>
        
        <div class="field form-group">
          <%= f.label :'制作物の画像' %>
          <%= f.file_field :production_picture, id: :production_picture %>
        </div>
        
        <div class="form-group">
          <%= f.label :'制作物の説明' %>
          <%= f.text_area :production_information, class: 'form-control', rows: 10 %>
        </div>
        
        <div class="form-group">
          <%= f.label :'制作物ジャンル' %>
          <%= f.text_area :production_genre, class: 'form-control', rows: 2 %>
        </div>
        
        <div class="form-group">
          <%= f.label :'制作物の季節' %>
          <%= f.text_area :production_season, class: 'form-control', rows: 2 %>
        </div>
        
        <!--<div class="field">-->
        
        <%= f.submit '出品・制作物をシェアする', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/productions/show.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
          
          <% if @production_show.status == true %>
           <h1>これはまだ購入できます</h1>
          <% else %>
            これはすでに購入されています
          <% end %>
          
          <div class="panel panel-default">
            
            <div class="panel-body">
              <p>商品タイトル</p>
              <p class="item-title production-title production-params"><%=  @production_show.production_title %></p>
            </div>
            <div class="panel-heading text-center">
              <p>商品画像</p>
              <!--<= production.production_picture %>-->
              <%= image_tag(@production_show.production_picture) if @production_show.production_picture.present? %>
              <!--<= image_tag(production.production_picture) %>-->
            </div>
            <div class="panel-body">
              <p>商品説明</p>
              <p class="production"><%=  @production_show.production_information %></p>
            </div>
            <div class="panel-body">
              <p>商品ジャンル</p>
              <p class="production"><%=  @production_show.production_genre %></p>
            </div>
            <div class="panel-body">
              <p>商品季節</p>
              <p class="production"><%=  @production_show.production_season %></p>
            </div>
          
          </div>
          
    <%= form_for(@production_comment, url:send_comment_path) do |f| %>
        <div class="form-group">
          <%= f.label :'コメント' %>
          <%= f.hidden_field :production_id, :value => params[:id] %>
        
         <% @display_comment.each do |comment| %>
          <div class="panel-body">
          <p class="production"><%= comment.user.nickname %>さん</p>
          <p class="production"><%= comment.content %></p>
          </div>
        <% end %>
    
        
          <% if @production_show.status == true %>
            <%= f.text_area :content, class: 'form-control', rows: 3 %>
            <%= f.submit 'コメントを投稿する', class: 'btn btn-primary btn-block' %>
          <% end %>
        </div>
    <% end %>
    
    <% if @production_show.status == true %>
    <%= link_to "購入する", {:controller => "productions", :action => "buy"},{class: 'btn btn-warning btn-block'} %>
    <% end %>
</div>
        
</div>

app/views/productions/transaction.html.erb
    <div class="panel panel-default">
      <div class="panel-body">
        <p>氏名</p>
        <p class="item-title production-title production-params"><%= @buyer.realname%>　様</p>
      </div>
      <div class="panel-body">
        <p>郵便番号</p>
        <p class="item-title production-title production-params">〒<%= @buyer.postalcode %></p>
      </div>
      <div class="panel-body">
        <p>住所</p>
        <p class="item-title production-title production-params"><%= @buyer.address %></p>
      </div>
      
    </div>
    
    <div class="panel panel-default">

        <%= form_for(@production_comment, url:send_transaction_comment_path) do |f| %>
          <div class="form-group">
            <%= f.label :'取引メッセージ' %>
            <%= f.hidden_field :production_id, :value => params[:id] %>
            <%= f.hidden_field :transaction_comment, :value => true %>
        
            <% @transaction_display_comment.each do |comment| %>
              <div class="panel-body">
                <p class="production"><%= comment.user.nickname %>さん</p>
                <p class="production"><%= comment.content %></p>
              </div>
            <% end %>
        
            <%= f.text_area :content, class: 'form-control', rows: 3 %>
        
        <%= f.submit '取引メッセージを送る', class: 'btn btn-danger btn-block' %>
        </div>
        <% end %>
      

            
            <div class="panel-body">
              <p>商品タイトル</p>
              <p class="item-title production-title production-params"><%=  @production.production_title %></p>
            </div>
            <div class="panel-heading text-center">
              <p>商品画像</p>
              <!--<= production.production_picture %>-->
              <%= image_tag(@production.production_picture) if @production.production_picture.present? %>
              <!--<= image_tag(production.production_picture) %>-->
            </div>
            <div class="panel-body">
              <p>商品説明</p>
              <p class="production"><%=  @production.production_information %></p>
            </div>
            <div class="panel-body">
              <p>商品ジャンル</p>
              <p class="production"><%=  @production.production_genre %></p>
            </div>
            <div class="panel-body">
              <p>商品季節</p>
              <p class="production"><%=  @production.production_season %></p>
            </div>
          
    </div>

app/views/toppages/index.html.erb
<div class="container">
  <div class="row mainlogo">
    <div class="col-md-12"></div>
  </div>
  
<!--------------------------------------------------------->
  
  <% if logged_in? %>
  <p>ログインできています　あなたのニックネームは　 <%= current_user.nickname %>　ですね。　</p>
  <% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <p>ログインしていません。</p>
    </div>
  </div>
  <% end %>

<!--------------------------------------------------------->
  
  <div class="row items">

     <% @productions.each do |production| %>
      
      <%= link_to production do %>
      
      <div class="item">
        <div class="col-md-3 col-sm-4 col-xs-12">
          
          
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <!--<= production.production_picture %>-->
              <%= image_tag(production.production_picture) if production.production_picture.present? %>
              <!--<= image_tag(production.production_picture) %>-->
            </div>
            <div class="panel-body">
              <p class="item-title production-title"> <%= production.production_title %> </p>
            </div>
          
          </div>
          
          
        </div>
        
        
      </div>
      
      <% end %>
      
    <% end %>
    <!------------------------------------------------------------------------------>
    
    
    <!----------------------------------------------->
    <!--< @productions.each do |production| %>-->
    
    <!--  <div class="item">-->
    <!--    <div class="col-md-3 col-sm-4 col-xs-12">-->
    <!--      <div class="panel panel-default">-->
    <!--        <div class="panel-heading text-center">-->
    <!--          <img src="" alt="商品画像" >-->
    <!--          <= image_tag(production.production_picture) %>-->
    <!--        </div>-->
    <!--        <div class="panel-body">-->
    <!--          <p class="item-title"> <= production.production_title %> </p>-->
    <!--        </div>-->
    <!--      </div>-->
    <!--    </div>-->
    <!--  </div>-->
      
    <!--< end %>-->
      

    <!----------------------------------------------->


  </div>
</div>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>ユーザ情報編集</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
    
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :nickname, '表示名' %>
        <%= f.text_field :nickname, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（再度入力してください）' %>
        <%= f.text_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :realname, '名前' %>
        <%= f.text_field :realname, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :postalcode, '郵便番号' %>
        <%= f.text_field :postalcode, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :address, '住所' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

      <%= f.submit '変更を保存する', class: 'btn btn-primary btn-block' %>
      <%= link_to "変更を保存する", {:controller => "users", :action => "update"},{class: 'btn btn-warning btn-block'} %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
    
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :nickname, '表示名' %>
        <%= f.text_field :nickname, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（再度入力してください）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '新規登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">私のニックネームは<%= @user.nickname %>　です</h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="" alt="ユーザ画像">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li><a href="#">出品成果物一覧</a></li>

      <% @productions.each do |production| %>
    
      <%= link_to production do %>
    
      <div class="item">
        <div class="col-md-3 col-sm-4 col-xs-12">
          
          
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <!--<= production.production_picture %>-->
              <%= image_tag(production.production_picture) if production.production_picture.present? %>
              <!--<= image_tag(production.production_picture) %>-->
            </div>
            <div class="panel-body">
              <p class="item-title production-title"> <%= production.production_title %> </p>
            </div>
          
          </div>
          
        </div>
        <% end %>
        
      </div>
    <% end %>

    </ul>
  </div>
</div>